### PR TITLE
pom 

### PR DESCRIPTION
**Pull request by Zerocreative0815**
#4

### CODE REVIEW

**Comment by nipafx** [comment]
Let's start working on this once we have a non-testing POM that actually works, i.e. when #3 is solved. Once that happens, please leave a comment here - I mainly operate based on the notifications GitHub sends me.

**Comment by Zerocreative0815** [comment]
and now i should create a pom with all the Junit 4 parts right?

**Comment by nipafx** [comment]
Yes, but I recommend to start with a new branch and close this PR.

**Comment by Zerocreative0815** [comment]
ok

**Pull request closed without merging**
