### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Zerocreative0815**
added the code of conduct to the readme....i think this should be the way we have to do it....

### CODE REVIEW

**Comment by nipafx** [comment]
Contributor covenant, good pick. Please put the CoC into its own file `CODE_OF_CONDUCT.md` and just reference it from the README.

**Comment by Zerocreative0815** [comment]
can the coc be written as a .txt file or have it to be a .md ?

**Comment by nipafx** [comment]
[GitHub proposes](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) to create an `.md` file. They do sometimes prescribe specific file names, so they can show the content in relevant places (like `README.md`). Just that the file ends in `.md` doesn't mean you have to translate the text into proper markdown, though. (Although I think there is a Markdown version of the Covenant CoC.)

**Comment by nipafx** [comment]
Oops, closed PR. Still relevant, though. :)

**Comment by Zerocreative0815** [comment]
but in textEDIT (mac) it automatically saves as a txt file... does it change to a .md if i write it in MArkdown?

**Comment by nipafx** [comment]
Proper editors (I have no idea whether I would cont textEDIT among them; don't know it) let you edit any text-based file. The difference between `.txt` and `.md` is just that: the file ending. Yes, people expect to find Markdown in a txt file but editors don't mind - both is pure text. (Unlike, e.g., word documents for example. Try opening them with a pure text editor and you'll that they are not text.)

**Pull request closed without merging**
