### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by Zerocreative0815**
added all mentions to the readme....

...i just want to create a PR for the readme...i made an extra branch for it so why do the other commits get into this pull request even they arent on the same branch at my forked repo?

### CODE REVIEW

**Comment by Zerocreative0815** [comment]
i don't get it.... i only want to made a PR for the last commit of the list....

i don't find a way to that...

**Comment by Zerocreative0815** [comment]
i just want to merge it and see what happen then...

**Comment by Zerocreative0815** [comment]
so i think it worked...or was it bad to merge it?

**Comment by nipafx** [comment]
> i only want to made a PR for the last commit of the list....

That doesn't work. When you open a pull request (or a manual `git merge` for that matter) from `X` into `master`, all commits on `X` that are not in `master` will be part of the PR and the eventuall merge.

> or was it bad to merge it?

I don't know whether it was bad, but it does need some cleaning up. I will comment on the issues.

**Comment by nipafx** [comment]
Also, please make sure to use the proper steps in the future, so you end up with clean branches that only contain changes for one specific task.

**Pull request merged**
