### PR TITLE
Leon versuch seinen Code hochzuladen

### PR DESCRIPTION
**Pull request by 0Y5**
hoffentlich klappt es

### CODE REVIEW

**Comment by Zerocreative0815** [comment]
nice titel dude :D

maybe a little to much for block 1....
let us wait for what mr. parlock will say to this

**Comment by nipafx** [comment]
There's a lot wrong with this pull request:

* The work was done on `master` instead of a separate branch.
* Title, description, and commit messages contain zero information what was done (yes, it's also a little funny).
* The PR contains code, which I doubt you have written. Why is it here? What does it do?
* There are a bunch of files that should not be in the repo, like `.DS_Store`, IntelliJ's `.idea` folder and `iml` file.
* Wow, there's also a submodule...

The PR contains very little of what you actually need to do - `pom.xml` at the most but that is incomplete.

I recommend to close the PR, reset `master` and start from the beginning.

**Comment by Zerocreative0815** [comment]
my thoughts were that the actual code for the first block is only a few lines. Something like: class fun val and println (for example)

**Comment by nipafx** [comment]
Yes, you only need like a dozen lines of code for the first block.

**Comment by Zerocreative0815** [comment]
But i can't write it as easy like this?
bildschirmfoto 2017-08-03 um 20 01 40

**Comment by nipafx** [comment]
Yes, that's perfectly fine, you don't even need `greeting` and `location`. In another issue you need to add some tests, though, and that's another few lines. Hence the "like a dozen".

**Pull request closed without merging**
