### PR TITLE
License

### PR DESCRIPTION
**Pull request by Zerocreative0815**
Added a license to the project which is simple but still good enough.

### CODE REVIEW

**Comment by nipafx** [comment]
Please make sure that a pull request contains a coherent set of changes. In this case that should be the license file and an entry in the README pointing to it. All other files need to be removed. It might be easiest to:

* merge some other PRs
* update your `master`
* create a new branch from it
* redo the one or two commits you need for this change

You can copy the license file and the README lines somewhere else to save them from Git's deletion.

**Comment by Zerocreative0815** [comment]
can i make a PR for particular commits?

**Comment by Zerocreative0815** [comment]
so the problem i see is that every time i do a PR every commit in my forked repo appears. My question is whether i can choose particular commits that i want to do a PR with?

**Comment by nipafx** [comment]
A pull request is always created from one branch to another, typically from the branch you created to work on a task (typically called _feature branch_) into the project's master branch. It proposes to merge all changes from the feature branch into master. The answer to your question is hence "jein":

* you can not select which commits you want to have in a pull request by picking them individually - it's always all of those that are on the feature but not on the master branch
* you can select which commits you want to have in a pull request by making sure your feature branch contains only those you care about

**Comment by nipafx** [comment]
> every commit in my forked repo 

No, every commit in your source branch. :smile:

**Comment by nipafx** [comment]
I guess you started on master, then created a branch _X_, made a few commits, and then created a new branch _Y_. That would have been a mistake, because now _Y_ contains all commits on _X_ and when you propose to merge _Y_ into master, the PR will contain too many changes.

**Comment by Zerocreative0815** [comment]
ok...
but i create a branch for every issue i worked on (.gitignore, license...) and pushed it directly from it an don't merge it to my local master. So on github i start the PR in the specific branch of every issue ...but why does the comits from the other branches appear in this PR?

**Comment by nipafx** [comment]
There are many different ways to screw up branches, I can not tell you, which one you chose. :wink: But have a look [at your license branch](https://github.com/Zerocreative0815/TeamProjectTH-BingenEP-1/commits/license), for example (you can pick other branches in the drop-down). It contains lots if license unrelated changes. Even your master branch has a lot of stuff that this repository's master doesn't contain (that should never happen).

Two small notes, then I will leave you with the recommendation to look at the Git and GitHub lectures again:

* be careful where you start a branch - this should always be master (and your master should never contain stuff upstream's master does not cotnain)
* you rarely need to use `git merge` - usually you will merge on GitHub

**Comment by Zerocreative0815** [comment]
Ok, thanks for the help  ;)

**Pull request closed without merging**
