### PR TITLE
false pom.xml i think

### PR DESCRIPTION
**Pull request by Zerocreative0815**
this is the short pom that gets created after the first time i create a pom in this project.

### CODE REVIEW

**Comment by Zerocreative0815** [comment]
@nicolaiparlog

**Comment by nipafx** [comment]
That looks like a default Java project POM. It lacks the configurations required to compile and test Kotlin. Have  a look at the energy model's POM for a version closer to what is required here.

**Comment by Zerocreative0815** [comment]
that's the point....at first it looked like the one from energy-model but then after i deleted it and did it again this one came up.
but i didn't change the way i create them..
@nicolaiparlog

**Comment by Zerocreative0815** [comment]
when i start the archetype thing i chose no.1014 for a simple maven project or something like that...was that wrong?

**Comment by nipafx** [comment]
I'm pretty sure that the first POM you had was not created by a Maven archetype. Anyways, instead of fiddling around with archetypes, I recommend to create the initial draft with a regular text editor and once that worked out, import the project into IntelliJ.

**Comment by Zerocreative0815** [comment]
but intelliJ won't let me import this txt file

**Comment by Zerocreative0815** [comment]
I don't get it...should i write the code in a txt file and then import it? because that doesn't work ..i tried it a few seconds ago

@nicolaiparlog

**Comment by nipafx** [comment]
You can use a regular text editor to create and edit a `pom.xml` file in the project's root folder (not in any subdirectory like `FirstApp`). If you're still not sure how it works, have a look at the Maven lecture and/or the linked tutorials.

**Pull request closed without merging**
